"""Corregir tipo de columna rol en Usuario y estado en TicketSoporte a usar ENUM

Revision ID: 0188e5a3e6bb
Revises: 
Create Date: 2025-10-13 13:31:38.516362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0188e5a3e6bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets_soporte', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('ABIERTO', 'EN_PROCESO', 'CERRADO', name='estadoticket'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets_soporte', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.Enum('ABIERTO', 'EN_PROCESO', 'CERRADO', name='estadoticket'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
