"""Añadir relacion SolicitudAyuda a TicketSoporte

Revision ID: d8292147d7f7
Revises: 0188e5a3e6bb
Create Date: 2025-10-13 17:25:55.221408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8292147d7f7'
down_revision = '0188e5a3e6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets_soporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_solicitud', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'solicitudes_ayuda', ['id_solicitud'], ['id_solicitud'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets_soporte', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_solicitud')

    # ### end Alembic commands ###
