"""agregar fecha_creacion a SolicitudAyuda

Revision ID: ea89db3d850e
Revises: d8292147d7f7
Create Date: 2025-10-22 21:16:45.633914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea89db3d850e'
down_revision = 'd8292147d7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_ayuda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.drop_column('fecha_solicitud')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=mysql.ENUM('USUARIO', 'ADMIN'),
               nullable=True,
               existing_server_default=sa.text("'USUARIO'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=mysql.ENUM('USUARIO', 'ADMIN'),
               nullable=False,
               existing_server_default=sa.text("'USUARIO'"))

    with op.batch_alter_table('solicitudes_ayuda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_solicitud', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###
